FROM almalinux:8 AS build

RUN dnf update -y \
    && dnf install -y \
    cmake \
    gcc \
    gcc-c++ \
    make \
    git \
    python3 \
    python3-pip \
    python3-devel

WORKDIR /

COPY . .

WORKDIR /tmp-build

RUN cmake /pythonfmu3/pythonfmu-export -DCMAKE_BUILD_TYPE=Release \
    && cmake --build . --config Release
    

# build wheel

FROM almalinux:8 AS wheel

RUN dnf install -y \
    python3 \
    python3-wheel

WORKDIR /

COPY . .

RUN python3 setup.py sdist bdist_wheel
